version: '3.4'

services:
    db:
        image: postgres:latest
        ports:
            - "5433:5432"
        volumes:
            - ./dump.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: postgres
            POSTGRES_DB: stdk
            POSTGRES_PASSWORD: postgres_pass

    crm:
        image: golang:1.11
        working_dir: /app
        command: ["./.bin/crm", ".bin/config.json"]
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        links:
            - db

    api:
        image: golang:1.11
        working_dir: /app
        command: ["./.bin/api", ".bin/config.json"]
        ports:
            - "8081:8081"
        volumes:
            - .:/app
        links:
            - db
